const teaData = [
  {
    id: 'teaset-001',
    imageOff: process.env.PUBLIC_URL + '/images/01_teaSet/teaset01_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/01_teaSet/teaset01_2.png',
    title: '깔라망고 & 리치피치 파티팩',
    desc: '콤부차 깔라망고 10입, 리치피치 1입, 제주섬 녹차 아몬드볼, 그린티 웨하스, 프리미엄 녹차와플, 고블렛 잔 2개, 머들러 1개, 쇼핑백 구성',
    price: 43200,
    group: 'teaset',
    tag : ['세트', '아이스티'],
    new: true,
    count: 10,
    typeBag: '쇼핑백 무료 동봉',
    typePack : '포장불가',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/01_teaSet/teaset01_3.jpg'
  },
  {
    id: 'teaset-002',
    imageOff: process.env.PUBLIC_URL + '/images/01_teaSet/teaset02_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/01_teaSet/teaset02_2.png',
    title: '동백이 피는 곶자왈 티타임 세트',
    desc: '오설록의 베스트 티 동백이 피는 곶자왈에 페어링 티푸드 녹차 와플을 곁들여 즐기는 티타임 세트',
    price: 20500,
    group: 'teaset',
    tag : ['세트', '티백'],
    new: false,
    count: 10,
    typeBag: '쇼핑백 무료 동봉',
    typePack : '포장불가',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/01_teaSet/teaset02_3.jpg'
  },
  {
    id: 'teaset-003',
    imageOff: process.env.PUBLIC_URL + '/images/01_teaSet/teaset03_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/01_teaSet/teaset03_2.png',
    title: '달빛걷기 티타임 세트',
    desc: '오설록의 베스트 티 달빛걷기에 페어링 티푸드 그린티 웨하스를 곁들여 즐기는 티타임 세트',
    price: 20500,
    group: 'teaset',
    tag : ['세트', '티백'],
    new: false,
    count: 10,
    typeBag: '쇼핑백 무료 동봉',
    typePack : '포장불가',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/01_teaSet/teaset03_3.jpg'
  },
  {
    id: 'teaset-004',
    imageOff: process.env.PUBLIC_URL + '/images/01_teaSet/teaset04_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/01_teaSet/teaset04_2.png',
    title: '상큼 블렌디드 티백 박스',
    desc: '제주만의 특별함을 담아내어 블렌딩한 프리미엄 티백 라인입니다. 삼다영귤티를 포함한 세트로, 상큼한 맛과 향을 좋아하는 분께 추천드립니다.',
    price: 29500,
    group: 'teaset',
    tag : ['세트', '티백'],
    new: false,
    count: 10,
    typeBag: '쇼핑백 무료 동봉',
    typePack : '무료포장(조립지함)',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/01_teaSet/teaset04_3.jpg'
  },
  {
    id: 'teaset-005',
    imageOff: process.env.PUBLIC_URL + '/images/01_teaSet/teaset05_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/01_teaSet/teaset05_2.png',
    title: '순수 블렌디드 티백 박스',
    desc: '제주만의 특별함을 담아내어 블렌딩한 프리미엄 티백 라인입니다. 제주순수녹차를 포함한 세트로, 당신의 순수한 마음을 선물하기에 좋습니다.',
    price: 29500,
    group: 'teaset',
    tag : ['세트', '티백'],
    new: false,
    count: 10,
    typeBag: '쇼핑백 무료 동봉',
    typePack : '무료포장(조립지함)',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/01_teaSet/teaset05_3.jpg'
  },
  {
    id: 'teaset-006',
    imageOff: process.env.PUBLIC_URL + '/images/01_teaSet/teaset06_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/01_teaSet/teaset06_2.png',
    title: '플로럴 티 박스',
    desc: '향기로운 티타임을 선사하는 홀리데이 기프트',
    price: 16500,
    group: 'teaset',
    tag : ['세트', '티백'],
    new: false,
    count: 10,
    typeBag: '쇼핑백 무료 동봉',
    typePack : '무료포장(조립지함)',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/01_teaSet/teaset06_3.jpg'
  },
  {
    id: 'teaset-007',
    imageOff: process.env.PUBLIC_URL + '/images/01_teaSet/teaset07_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/01_teaSet/teaset07_2.png',
    title: '아이스 산호섬 티푸드 세트',
    desc: '언제 어디서든 시원하게 아이스티와 함께 티타임을 즐길 수 있는 아이스 텀블러 세트 (산호섬 20입, 그린티 웨하스, 녹차 와플, 아이스 텀블러, 쇼핑백 구성)',
    price: 32500,
    group: 'teaset',
    tag : ['세트', '아이스티'],
    new: false,
    count: 10,
    typeBag: '쇼핑백 무료 동봉',
    typePack : '포장불가',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/01_teaSet/teaset07_3.jpg'
  },
  {
    id: 'teaset-008',
    imageOff: process.env.PUBLIC_URL + '/images/01_teaSet/teaset08_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/01_teaSet/teaset08_2.png',
    title: '세작 잎차 선물세트',
    desc: '고급 케이스에 제주 차밭의 어린 찻잎으로 만든 작설차 세작과 차칙을 함께 담은 선물 세트 (세작 80g, 차칙, 고급 케이스, 쇼핑백 구성)',
    price: 48000,
    group: 'teaset',
    tag : ['세트', '잎차'],
    new: false,
    count: 10,
    typeBag: '쇼핑백 무료 동봉',
    typePack : '무료포장(조립지함)',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/01_teaSet/teaset08_3.jpg'
  },
  {
    id: 'teaset-009',
    imageOff: process.env.PUBLIC_URL + '/images/01_teaSet/teaset09_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/01_teaSet/teaset09_2.png',
    title: '시그니처 기프트 세트',
    desc: '오설록의 시그니처 티 3종과 그린티 웨하스를 한꺼번에 선물하기 좋은 기프트 세트',
    price: 22500,
    group: 'teaset',
    tag : ['세트', '티백'],
    new: false,
    count: 10,
    typeBag: '쇼핑백 무료 동봉',
    typePack : '무료포장(조립지함)',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/01_teaSet/teaset09_3.jpg'
  },
  {
    id: 'teaset-010',
    imageOff: process.env.PUBLIC_URL + '/images/01_teaSet/teaset10_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/01_teaSet/teaset10_2.png',
    title: '베스트 티 컬렉션 3종',
    desc: '일상의 기념일, 작은 선물을 위한 오설록 베스트 블렌디드티 큐브 세트',
    price: 25000,
    group: 'teaset',
    tag : ['세트', '티백'],
    new: false,
    count: 10,
    typeBag: '쇼핑백 무료 동봉',
    typePack : '포장가능',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/01_teaSet/teaset10_3.jpg'
  },
  {
    id: 'teaset-011',
    imageOff: process.env.PUBLIC_URL + '/images/01_teaSet/teaset11_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/01_teaSet/teaset11_2.png',
    title: '그린티 스트레이너 키트',
    desc: '여유롭고 차분히 혼자만의 리추얼을 즐길 수 있는 그린티 키트 (세작 40g, 와플, 웨하스, 티 스트레이너, 모래시계, 쇼핑백 구성)',
    price: 39500,
    group: 'teaset',
    tag : ['세트', '잎차'],
    new: false,
    count: 10,
    typeBag: '쇼핑백 무료 동봉',
    typePack : '포장불가',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/01_teaSet/teaset11_3.jpg'
  },
  {
    id: 'teaset-012',
    imageOff: process.env.PUBLIC_URL + '/images/01_teaSet/teaset12_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/01_teaSet/teaset12_2.png',
    title: '베스트 티 컬렉션 9종',
    desc: '순수차, 블렌디드티, 허브티를 모두 경험할 수 있는 오설록 베스트 티 선물세트',
    price: 62000,
    group: 'teaset',
    tag : ['세트', '티백'],
    new: false,
    count: 10,
    typeBag: '쇼핑백 무료 동봉',
    typePack : '포장가능',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/01_teaSet/teaset12_3.jpg'
  },
  {
    id: 'teaset-013',
    imageOff: process.env.PUBLIC_URL + '/images/01_teaSet/teaset13_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/01_teaSet/teaset13_2.png',
    title: '달달 블렌디드 티백 박스',
    desc: '제주만의 특별함을 담아내어 블렌딩한 프리미엄 티백 라인입니다. 그 중에서도 달달한 맛과 향을 가진 제품을 3가지 모은 세트입니다.',
    price: 29500,
    group: 'teaset',
    tag : ['세트', '티백'],
    new: false,
    count: 10,
    typeBag: '쇼핑백 무료 동봉',
    typePack : '무료포장(조립지함)',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/01_teaSet/teaset13_3.jpg'
  },
  {
    id: 'teaset-014',
    imageOff: process.env.PUBLIC_URL + '/images/01_teaSet/teaset14_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/01_teaSet/teaset14_2.png',
    title: '허브티 컬렉션',
    desc: '남녀노소 즐기기 좋은 오설록 대표 허브티 3종 세트',
    price: 25000,
    group: 'teaset',
    tag : ['세트', '티백'],
    new: false,
    count: 10,
    typeBag: '쇼핑백 무료 동봉',
    typePack : '포장불가',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/01_teaSet/teaset14_3.jpg'
  },
  {
    id: 'teaset-015',
    imageOff: process.env.PUBLIC_URL + '/images/01_teaSet/teaset15_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/01_teaSet/teaset15_2.png',
    title: '녹차 밀크 스프레드 세트',
    desc: '녹차스프레드와 별도 포장이 필요 없는 고급 패키지로 구성된 쨈 2종 세트입니다.',
    price: 20000,
    group: 'teaset',
    tag : ['세트', '스프레드'],
    new: false,
    count: 10,
    typeBag: '쇼핑백 무료 동봉',
    typePack : '무료포장(조립지함)',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/01_teaSet/teaset15_3.jpg'
  },
  {
    id: 'teaset-016',
    imageOff: process.env.PUBLIC_URL + '/images/01_teaSet/teaset16_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/01_teaSet/teaset16_2.png',
    title: '과일 블렌디드 티백 박스',
    desc: '제주만의 특별함을 담아내어 블렌딩한 프리미엄 티백 라인입니다. 새콤달콤한 여러 과실향의 제품을 다양하게 즐길 수 있는 세트입니다.',
    price: 29500,
    group: 'teaset',
    tag : ['세트', '티백'],
    new: false,
    count: 10,
    typeBag: '쇼핑백 무료 동봉',
    typePack : '포장불가',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/01_teaSet/teaset16_3.jpg'
  },
  {
    id: 'teaset-017',
    imageOff: process.env.PUBLIC_URL + '/images/01_teaSet/teaset17_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/01_teaSet/teaset17_2.png',
    title: '베스트 블렌디드 티백 박스',
    desc: '제주만의 특별함을 담아내어 블렌딩한 프리미엄 티백 라인입니다. 그윽한 후발효차의 은은한 풍미를 다양하게 즐길 수 있는 세트입니다.',
    price: 29500,
    group: 'teaset',
    tag : ['세트', '티백'],
    new: false,
    count: 10,
    typeBag: '쇼핑백 무료 동봉',
    typePack : '무료포장(조립지함)',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/01_teaSet/teaset17_3.jpg'
  },
  {
    id: 'teaset-018',
    imageOff: process.env.PUBLIC_URL + '/images/01_teaSet/teaset18_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/01_teaSet/teaset18_2.png',
    title: '메모리 인 제주 40입',
    desc: '제주 꽃길에서 느꼈던 설렘의 향기와 달콤했던 사랑의 추억을 떠 올려줄 제주 꽃을 모티브로 한 티 4종 세트입니다.',
    price: 68000,
    group: 'teaset',
    tag : ['세트', '잎차'],
    new: false,
    count: 10,
    typeBag: '쇼핑백 무료 동봉',
    typePack : '포장가능',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/01_teaSet/teaset18_3.jpg'
  },
  {
    id: 'teaset-019',
    imageOff: process.env.PUBLIC_URL + '/images/01_teaSet/teaset19_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/01_teaSet/teaset19_2.png',
    title: '티 모먼트',
    desc: '오설록의 티백 라인을 10종으로 다양하게, 50입으로 넉넉하게 만나는 온라인 한정 티 세트',
    price: 35000,
    group: 'teaset',
    tag : ['세트', '티백'],
    new: false,
    count: 10,
    typeBag: '쇼핑백 무료 동봉',
    typePack : '포장가능',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/01_teaSet/teaset19_3.jpg'
  },
  {
    id: 'teaset-020',
    imageOff: process.env.PUBLIC_URL + '/images/01_teaSet/teaset20_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/01_teaSet/teaset20_2.png',
    title: '스페셜 티 에디션',
    desc: '오설록의 시그니처 티를 모두 경험할 수 있는 프리미엄 선물 세트',
    price: 95000,
    group: 'teaset',
    tag : ['세트', '티백'],
    new: false,
    count: 10,
    typeBag: '쇼핑백 무료 동봉',
    typePack : '포장가능',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/01_teaSet/teaset20_3.jpg'
  },
  {
    id: 'teaset-021',
    imageOff: process.env.PUBLIC_URL + '/images/01_teaSet/teaset21_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/01_teaSet/teaset21_2.png',
    title: '프리미엄 티 컬렉션 90입',
    desc: '고급 지함에 다양한 맛과 향의 차가 담겨있어 따뜻한 진심을 전하기에 좋은 선물세트입니다.',
    price: 70000,
    group: 'teaset',
    tag : ['세트', '티백'],
    new: false,
    count: 10,
    typeBag: '쇼핑백 무료 동봉',
    typePack : '포장가능',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/01_teaSet/teaset21_3.jpg'
  },
  {
    id: 'teaset-022',
    imageOff: process.env.PUBLIC_URL + '/images/01_teaSet/teaset22_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/01_teaSet/teaset22_2.png',
    title: '신 오브 제주',
    desc: '제주의 아름다운 숨은 비경을 담은 블렌디드 티 모음 세트 입니다. 다양한 블렌디드 티를 좋아하시는 분께 선물하시기 좋은 제품입니다.',
    price: 27000,
    group: 'teaset',
    tag : ['세트', '티백'],
    new: false,
    count: 10,
    typeBag: '쇼핑백 무료 동봉',
    typePack : '포장가능',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/01_teaSet/teaset22_3.jpg'
  },
  {
    id: 'teaset-023',
    imageOff: process.env.PUBLIC_URL + '/images/01_teaSet/teaset23_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/01_teaSet/teaset23_2.png',
    title: '메모리 인 제주 20입',
    desc: '제주 꽃길에서 느꼈던 설렘의 향기와 달콤했던 사랑의 추억을 떠 올려줄 제주 꽃을 모티브로 한 BEST TEA SET 입니다.',
    price: 38000,
    group: 'teaset',
    tag : ['세트', '티백'],
    new: false,
    count: 10,
    typeBag: '쇼핑백 무료 동봉',
    typePack : '포장가능',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/01_teaSet/teaset23_3.jpg'
  },
  {
    id: 'teaset-024',
    imageOff: process.env.PUBLIC_URL + '/images/01_teaSet/teaset24_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/01_teaSet/teaset24_2.png',
    title: '시크릿 티 스토리',
    desc: '신비로운 섬 제주의 다채로운 향기와 이야기를 품은, 취향 걱정없이 선물하기 좋은 고급스러운 구성의 선물 세트',
    price: 45000,
    group: 'teaset',
    tag : ['세트', '티백'],
    new: false,
    count: 10,
    typeBag: '쇼핑백 무료 동봉',
    typePack : '포장가능',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/01_teaSet/teaset24_3.jpg'
  },
  {
    id: 'teaset-025',
    imageOff: process.env.PUBLIC_URL + '/images/01_teaSet/teaset25_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/01_teaSet/teaset25_2.png',
    title: '마스터 블렌드',
    desc: '마스터의 블렌딩으로 탄생한 오설록만의 제주의 향기를 담은 대표 블렌디드 티 모음 세트',
    price: 53000,
    group: 'teaset',
    tag : ['세트', '티백'],
    new: false,
    count: 10,
    typeBag: '쇼핑백 무료 동봉',
    typePack : '포장가능',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/01_teaSet/teaset25_3.jpg'
  },
  {
    id: 'teaset-026',
    imageOff: process.env.PUBLIC_URL + '/images/01_teaSet/teaset26_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/01_teaSet/teaset26_2.png',
    title: '프리미엄 티 컬렉션',
    desc: '취향과 기분에 따라 다채로운 맛과 향을 즐기기 좋은, 알찬 구성의 베스트셀러 티 세트',
    price: 28000,
    group: 'teaset',
    tag : ['세트', '티백'],
    new: false,
    count: 10,
    typeBag: '쇼핑백 무료 동봉',
    typePack : '포장가능',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/01_teaSet/teaset26_3.jpg'
  },
  {
    id: 'teaset-027',
    imageOff: process.env.PUBLIC_URL + '/images/01_teaSet/teaset27_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/01_teaSet/teaset27_2.png',
    title: '러블리 티 박스',
    desc: '즐겁고 행복한 티타임을 선사하는 달콤하고 향긋한 오설록만의 특별한 블렌디드 티 선물 세트',
    price: 20000,
    group: 'teaset',
    tag : ['세트', '티백'],
    new: false,
    count: 10,
    typeBag: '쇼핑백 무료 동봉',
    typePack : '포장가능',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/01_teaSet/teaset27_3.jpg'
  },

  {
    id: 'master-001',
    imageOff: process.env.PUBLIC_URL + '/images/02_masterpiece/master01_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/02_masterpiece/master01_2.png',
    title: '홍우전 60g',
    desc: '이른 아침부터 늦은 저녁까지 계속 발효하여, 붉은 노을을 닮은 붉고 진한 수색과 풍부한 향기를 즐겨보세요.',
    price: 99000,
    group: 'masterpiece',
    tag : '잎차',
    new: false,
    count: 10,
    typeBag: '쇼핑백 무료 동봉',
    typePack : '포장불가',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/02_masterpiece/master01_3.jpg'
  },
  {
    id: 'master-002',
    imageOff: process.env.PUBLIC_URL + '/images/02_masterpiece/master02_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/02_masterpiece/master02_2.png',
    title: '월출향 60g',
    desc: '오설록의 월출산 차밭에서 이른 봄 돋아난 첫 새싹만 정성껏 발효하고 덖었습니다. 월출산 자락의 향미를 즐겨보세요.',
    price: 90000,
    group: 'masterpiece',
    tag : '잎차',
    new: false,
    count: 10,
    typeBag: '쇼핑백 무료 동봉',
    typePack : '포장불가',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/02_masterpiece/master02_3.jpg'
  },
  {
    id: 'master-003',
    imageOff: process.env.PUBLIC_URL + '/images/02_masterpiece/master03_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/02_masterpiece/master03_2.png',
    title: '일로향 60g',
    desc: '어린 차싹의 형상을 그대로 간직한 오설록의 최고 명차입니다. 중요한 분께 가치있는 선물로 추천합니다.',
    price: 170000,
    group: 'masterpiece',
    tag : '잎차',
    new: false,
    count: 10,
    typeBag: '쇼핑백 무료 동봉',
    typePack : '무료포장',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/02_masterpiece/master03_3.jpg'
  },
  {
    id: 'master-004',
    imageOff: process.env.PUBLIC_URL + '/images/02_masterpiece/master04_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/02_masterpiece/master04_2.png',
    title: '우전 60g',
    desc: '가장 먼저 딴 여린 차순을 정성스레 덖어낸 오설록 고급 우전차입니다.',
    price: 70000,
    group: 'masterpiece',
    tag : '잎차',
    new: false,
    count: 10,
    typeBag: '쇼핑백 무료 동봉',
    typePack : '포장불가',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/02_masterpiece/master04_3.jpg'
  },
  {
    id: 'master-005',
    imageOff: process.env.PUBLIC_URL + '/images/02_masterpiece/master05_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/02_masterpiece/master05_2.png',
    title: '마스터즈 세트',
    desc: '오설록의 대표 명차로만 구성한 프리미엄 기프트',
    price: 230000,
    group: ['masterpiece', 'teaset'],
    tag : '잎차',
    new: false,
    count: 10,
    typePack : '포장가능',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/02_masterpiece/master05_3.jpg'
  },

  {
    id: 'green-001',
    imageOff: process.env.PUBLIC_URL + '/images/03_greenTea/green01_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/03_greenTea/green01_1.png',
    title: '말차 스틱',
    desc: '물이나 우유에 편리하게 타먹는 달콤한 말차(가루 녹차)',
    price: 10000,
    group: 'greentea',
    tag : '가루',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/03_greenTea/green01_3.png'
  },
  {
    id: 'green-002',
    imageOff: process.env.PUBLIC_URL + '/images/03_greenTea/green02_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/03_greenTea/green02_2.png',
    title: '세작 3입',
    desc: '제주 차밭의 어린 찻잎으로 만든 작설차를 처음 접하시거나 다양한 차를 조금씩 맛보고 싶으시다면, 3입 제품으로 합리적인 가격에 체험해보세요.',
    price: 5000,
    group: 'greentea',
    tag : '잎차',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/03_greenTea/green02_3.jpg'
  },
  {
    id: 'green-003',
    imageOff: process.env.PUBLIC_URL + '/images/03_greenTea/green03_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/03_greenTea/green03_2.png',
    title: '세작 10입',
    desc: '제주 차밭의 어린 찻잎으로 만든 작설차',
    price: 17000,
    group: 'greentea',
    tag : '잎차',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD : true,
    info : process.env.PUBLIC_URL + '/images/03_greenTea/green03_3.jpg'
  },
  {
    id: 'green-004',
    imageOff: process.env.PUBLIC_URL + '/images/03_greenTea/green04_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/03_greenTea/green04_2.png',
    title: '제주 순수녹차',
    desc: '어린 찻잎만을 살짝 찌고 덖어, 부드럽고 깔끔한 맛의 녹차입니다. 제주 차밭의 맛과 향을 가벼운 가격으로 즐겨보세요.',
    price: 9500,
    group: 'greentea',
    tag : '티백',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/03_greenTea/green04_3.jpg',
  },
  {
    id: 'green-005',
    imageOff: process.env.PUBLIC_URL + '/images/03_greenTea/green05_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/03_greenTea/green05_2.png',
    title: '프리미엄 말차',
    desc: '어린 찻잎을 정성껏 갈아 만든 깊은 풍미의 유기농 말차',
    price: 23000,
    group: 'greentea',
    tag : '가루',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD: true,
    info : process.env.PUBLIC_URL + '/images/03_greenTea/green05_3.jpg',
  },
  {
    id: 'green-006',
    imageOff: process.env.PUBLIC_URL + '/images/03_greenTea/green06_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/03_greenTea/green06_2.png',
    title: '세작 80g',
    desc: '제주 차밭의 어린 찻잎으로 만든 작설차',
    price: 28000,
    group: 'greentea',
    tag : '잎차',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD: true,
    info : process.env.PUBLIC_URL + '/images/03_greenTea/green06_3.jpg',
  },
  {
    id: 'green-007',
    imageOff: process.env.PUBLIC_URL + '/images/03_greenTea/green07_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/03_greenTea/green07_2.png',
    title: '덖음차 50g',
    desc: '깨끗한 제주의 신선한 찻잎을 정성스레 덖은 녹차입니다. 부담없는 가격으로 오설록의 녹차를 즐길 수 있습니다.',
    price: 15000,
    group: 'greentea',
    tag : '잎차',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD : true,
    info : process.env.PUBLIC_URL + '/images/03_greenTea/green07_3.jpg'
  },
  {
    id: 'green-008',
    imageOff: process.env.PUBLIC_URL + '/images/03_greenTea/green08_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/03_greenTea/green08_2.png',
    title: '가루 녹차',
    desc: '제주 오설록 직영 차밭에서 100% 유기농으로 재배한 프리미엄 가루 녹차입니다. 어디에나 간편하게 톡톡 뿌려 즐기실 수 있습니다.',
    price: 10000,
    group: 'greentea',
    tag : '가루',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/03_greenTea/green08_3.jpg'
  },
  {
    id: 'green-009',
    imageOff: process.env.PUBLIC_URL + '/images/03_greenTea/green09_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/03_greenTea/green09_2.png',
    title: '찬물 녹차',
    desc: '찬물에서 쉽게 우러나는 부드럽고 깔끔한 스틱형 녹차 아이스티입니다.',
    price: 9000,
    group: ['greentea', 'icedtea'],
    tag : '티백',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/03_greenTea/green09_3.jpg'
  },
  {
    id: 'green-010',
    imageOff: process.env.PUBLIC_URL + '/images/03_greenTea/green10_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/03_greenTea/green10_2.png',
    title: '세작 20입',
    desc: '제주 차밭의 어린 찻잎으로 만든 작설차를 피라미드 티백으로 간편하게, 합리적인 가격으로 즐겨보세요.',
    price: 10000,
    group: 'greentea',
    tag : '티백',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD : true,
    info : process.env.PUBLIC_URL + '/images/03_greenTea/green10_3.jpg'
  },
  {
    id: 'green-011',
    imageOff: process.env.PUBLIC_URL + '/images/03_greenTea/green11_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/03_greenTea/green11_2.png',
    title: '세작 40g',
    desc: '제주 차밭의 어린 찻잎으로 만든 작설차를 원하는 용량만큼 우려드실 수 있는 잎차입니다. 합리적인 가격에 즐겨보세요.',
    price: 17000,
    group: 'greentea',
    tag : '가루',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD : true,
    info : process.env.PUBLIC_URL + '/images/03_greenTea/green11_3.jpg'
  },

  {
    id: 'black-001',
    imageOff: process.env.PUBLIC_URL + '/images/04_blackTea/black01_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/04_blackTea/black01_2.png',
    title: '삼다연 10입',
    desc: '제주 삼나무로 오랜 시간 숙성시킨 깊고 부드러운 후발효차',
    price: 15000,
    group: 'blacktea',
    tag : '티백',
    new: false,
    count: 0,
    typePack : '포장불가',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/04_blackTea/black01_3.jpg'
  },
  {
    id: 'black-002',
    imageOff: process.env.PUBLIC_URL + '/images/04_blackTea/black02_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/04_blackTea/black02_2.png',
    title: '제주숲홍차 10입',
    desc: '제주 숲 차밭의 어린 찻잎으로 만든 산뜻한 향미의 홍차',
    price: 15000,
    group: 'blacktea',
    tag : '티백',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/04_blackTea/black02_3.jpg'
  },
  {
    id: 'black-003',
    imageOff: process.env.PUBLIC_URL + '/images/04_blackTea/black03_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/04_blackTea/black03_2.png',
    title: '제주화산암차 50g',
    desc: '제주 삼나무로 오랜 시간 숙성시킨 깊고 부드러운 후발효차',
    price: 15000,
    group: 'blacktea',
    tag : '잎차',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/04_blackTea/black03_3.jpg'
  },
  {
    id: 'black-004',
    imageOff: process.env.PUBLIC_URL + '/images/04_blackTea/black04_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/04_blackTea/black04_2.png',
    title: '청우롱 50g',
    desc: '제주의 따뜻한 햇살로 약발효한 부드러운 향미의 우롱차',
    price: 35000,
    group: 'blacktea',
    tag : '잎차',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/04_blackTea/black04_3.jpg'
  },
  {
    id: 'black-005',
    imageOff: process.env.PUBLIC_URL + '/images/04_blackTea/black05_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/04_blackTea/black05_2.png',
    title: '제주화산암차 10입',
    desc: '제주의 따뜻한 햇살로 약발효한 부드러운 향미의 우롱차',
    price: 35000,
    group: 'blacktea',
    tag : '티백',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD : true,
    info : process.env.PUBLIC_URL + '/images/04_blackTea/black05_3.jpg'
  },
  {
    id: 'black-006',
    imageOff: process.env.PUBLIC_URL + '/images/04_blackTea/black05_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/04_blackTea/black05_2.png',
    title: '삼다연 80g',
    desc: '제주의 따뜻한 햇살로 약발효한 부드러운 향미의 우롱차',
    price: 40000,
    group: 'blacktea',
    tag : '잎차',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/04_blackTea/black05_3.jpg'
  },
  {
    id: 'black-007',
    imageOff: process.env.PUBLIC_URL + '/images/04_blackTea/black07_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/04_blackTea/black07_2.png',
    title: '청우롱 10입',
    desc: '제주의 따뜻한 햇살로 약발효한 부드러운 향미의 우롱차',
    price: 15000,
    group: 'blacktea',
    tag : '티백',
    new: false,
    count: 0,
    typePack : '포장불가',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/04_blackTea/black07_3.jpg'
  },
  {
    id: 'black-008',
    imageOff: process.env.PUBLIC_URL + '/images/04_blackTea/black08_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/04_blackTea/black08_2.png',
    title: '제주화산암차 3입',
    desc: '한라산의 화산암석층이 키워낸 구수한 풍미의 반발효차',
    price: 4500,
    group: 'blacktea',
    tag : '티백',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/04_blackTea/black08_3.jpg'
  },
  {
    id: 'black-009',
    imageOff: process.env.PUBLIC_URL + '/images/04_blackTea/black09_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/04_blackTea/black09_2.png',
    title: '제주 얼그레이',
    desc: '제주산 홍차에 천연 베르가못향을 더한 클래식 얼그레이입니다. 제주 차밭의 맛과 향을 가벼운 가격으로 즐겨보세요.',
    price: 9500,
    group: 'blacktea',
    tag : '티백',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/04_blackTea/black09_3.jpg'
  },
  {
    id: 'black-010',
    imageOff: process.env.PUBLIC_URL + '/images/04_blackTea/black10_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/04_blackTea/black10_2.png',
    title: '제주숲홍차 80g',
    desc: '제주 숲 차밭의 어린 찻잎으로 만든 산뜻한 향미의 홍차',
    price: 40000,
    group: 'blacktea',
    tag : '잎차',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/04_blackTea/black10_3.jpg'
  },
  {
    id: 'black-011',
    imageOff: process.env.PUBLIC_URL + '/images/04_blackTea/black11_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/04_blackTea/black11_2.png',
    title: '제주화산암차 20입',
    desc: '한라산의 화산암석층이 키워낸 구수한 풍미의 반발효차',
    price: 23000,
    group: 'blacktea',
    tag : '티백',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD : true,
    info : process.env.PUBLIC_URL + '/images/04_blackTea/black11_3.jpg'
  },
  {
    id: 'black-012',
    imageOff: process.env.PUBLIC_URL + '/images/04_blackTea/black12_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/04_blackTea/black12_2.png',
    title: '제주 화산우롱차',
    desc: '깊은 로스팅 풍미의 제주 화산섬 반발효차입니다. 제주 차밭의 맛과 향을 가벼운 가격으로 즐겨보세요.',
    price: 9500,
    group: 'blacktea',
    tag : '티백',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/04_blackTea/black12_3.jpg'
  },
  {
    id: 'black-013',
    imageOff: process.env.PUBLIC_URL + '/images/04_blackTea/black13_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/04_blackTea/black13_2.png',
    title: '제주화산암차 30g',
    desc: '한라산의 화산암석층이 키워낸 구수한 풍미의 반발효차',
    price: 15000,
    group: 'blacktea',
    tag : '잎차',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD : true,
    info : process.env.PUBLIC_URL + '/images/04_blackTea/black13_3.jpg'
  },
  
  {
    id: 'blended-001',
    imageOff: process.env.PUBLIC_URL + '/images/05_blendedTea/blended01_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/05_blendedTea/blended01_2.png',
    title: '동백이 피는 곶자왈 35g',
    desc: '제주 동백꽃향과 열대과일의 달콤한 풍미가 매력적인 블렌디드티',
    price: 15000,
    group: 'blendedtea',
    tag : '잎차',
    new: false,
    count: 0,
    typePack : '포장불가',
    RD : true,
    info : process.env.PUBLIC_URL + '/images/05_blendedTea/blended01_3.jpg'
  },
  {
    id: 'blended-002',
    imageOff: process.env.PUBLIC_URL + '/images/05_blendedTea/blended02_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/05_blendedTea/blended02_2.png',
    title: '구름노래 10입',
    desc: '제주 하늘의 구름처럼 부드러운 우유 향과 복숭아 향이 감도는 블렌디드 티',
    price: 15000,
    group: 'blendedtea',
    tag : '티백',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/05_blendedTea/blended02_3.jpg'
  },
  {
    id: 'blended-003',
    imageOff: process.env.PUBLIC_URL + '/images/05_blendedTea/blended03_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/05_blendedTea/blended03_2.png',
    title: '삼다연 제주영귤 3입',
    desc: '제주 삼나무의 그윽한 풍미에 제주영귤의 싱그러움을 더한 후발효차를 처음 접하시거나 다양한 차를 조금씩 맛보고 싶으시다면, 3입 제품으로 합리적인 가격에 체험해보세요.',
    price: 4500,
    group: 'blendedtea',
    tag : '티백',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/05_blendedTea/blended03_3.jpg'
  },
  {
    id: 'blended-004',
    imageOff: process.env.PUBLIC_URL + '/images/05_blendedTea/blended04_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/05_blendedTea/blended04_2.png',
    title: '동백이 피는 곶자왈 3입',
    desc: '제주 동백꽃향과 열대과일의 달콤한 풍미가 매력적인 블렌디드티를 처음 접하시거나 다양한 차를 조금씩 맛보고 싶으시다면, 3입 제품으로 합리적인 가격에 체험해보세요.',
    price: 4500,
    group: 'blendedtea',
    tag : '티백',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/05_blendedTea/blended04_3.jpg'
  },
  {
    id: 'blended-005',
    imageOff: process.env.PUBLIC_URL + '/images/05_blendedTea/blended05_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/05_blendedTea/blended05_2.png',
    title: '벚꽃향 가득한 올레 3입',
    desc: '제주 왕벚꽃향의 화사함에 달콤새콤한 과실향이 어우러진 블렌디드티를 처음 접하시거나 다양한 차를 조금씩 맛보고 싶으시다면, 3입 제품으로 합리적인 가격에 체험해보세요.',
    price: 4500,
    group: 'blendedtea',
    tag : '티백',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/05_blendedTea/blended05_3.jpg'
  },
  {
    id: 'blended-006',
    imageOff: process.env.PUBLIC_URL + '/images/05_blendedTea/blended06_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/05_blendedTea/blended06_2.png',
    title: '스윗 베리 루이보스티',
    desc: '상큼한 라즈베리와 은은한 카라멜향이 조화롭게 어우러진 블렌디드 허브티',
    price: 9500,
    group: 'blendedtea',
    tag : '티백',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/05_blendedTea/blended06_3.jpg'
  },
  {
    id: 'blended-007',
    imageOff: process.env.PUBLIC_URL + '/images/05_blendedTea/blended07_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/05_blendedTea/blended07_2.png',
    title: '귤꽃향을 품은 우잣담 3입',
    desc: '제주 귤꽃향의 싱그러움에 감귤의 상큼함을 더한 블렌디드티를 처음 접하시거나 다양한 차를 조금씩 맛보고 싶으시다면, 3입 제품으로 합리적인 가격에 체험해보세요.',
    price: 4500,
    group: 'blendedtea',
    tag : '티백',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/05_blendedTea/blended07_3.jpg'
  },
  {
    id: 'blended-008',
    imageOff: process.env.PUBLIC_URL + '/images/05_blendedTea/blended08_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/05_blendedTea/blended08_2.png',
    title: '웨딩 그린티 3입',
    desc: '신부의 부케가 꽃향이 만발하는 한잔의 차가 되었습니다. 다양한 차를 조금씩 맛보고 싶으시다면, 3입 제품으로 합리적인 가격에 체험해보세요.',
    price: 4500,
    group: 'blendedtea',
    tag : '티백',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/05_blendedTea/blended08_3.jpg'
  },
  {
    id: 'blended-009',
    imageOff: process.env.PUBLIC_URL + '/images/05_blendedTea/blended09_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/05_blendedTea/blended09_2.png',
    title: '레드파파야 블랙티 3입',
    desc: '붉은 장미와 달콤한 파파야가 곁들여진 화려한 풍미의 홍차를 처음 접하시거나 다양한 차를 조금씩 맛보고 싶으시다면, 3입 제품으로 합리적인 가격에 체험해보세요.',
    price: 4500,
    group: 'blendedtea',
    tag : '티백',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/05_blendedTea/blended09_3.jpg'
  },
  {
    id: 'blended-010',
    imageOff: process.env.PUBLIC_URL + '/images/05_blendedTea/blended10_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/05_blendedTea/blended10_2.png',
    title: '비의 사색 10입',
    desc: '신부의 부케가 꽃향이 만발하는 한잔의 차가 되었습니다. 다양한 차를 조금씩 맛보고 싶으시다면, 3입 제품으로 합리적인 가격에 체험해보세요.',
    price: 4500,
    group: 'blendedtea',
    tag : '티백',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/05_blendedTea/blended10_3.jpg'
  },
  {
    id: 'blended-011',
    imageOff: process.env.PUBLIC_URL + '/images/05_blendedTea/blended11_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/05_blendedTea/blended11_2.png',
    title: '트로피컬 블랙티',
    desc: '제주산 홍차와 열대과일의 새콤달콤한 풍미로 기분까지 좋아지는 블렌디드 티입니다. 제주 차밭의 맛과 향을 가벼운 가격으로 즐겨보세요.',
    price: 15000,
    group: 'blendedtea',
    tag : '티백',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/05_blendedTea/blended11_3.jpg'
  },
  {
    id: 'blended-012',
    imageOff: process.env.PUBLIC_URL + '/images/05_blendedTea/blended12_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/05_blendedTea/blended12_2.png',
    title: '동백이 피는 곶자왈 10입',
    desc: '제주 동백꽃향과 열대과일의 달콤한 풍미가 매력적인 블렌디드티를 소중한 사람에게 선물해보세요.',
    price: 15000,
    group: 'blendedtea',
    tag : '티백',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD: true,
    info : process.env.PUBLIC_URL + '/images/05_blendedTea/blended12_3.jpg'
  },
  {
    id: 'blended-013',
    imageOff: process.env.PUBLIC_URL + '/images/05_blendedTea/blended13_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/05_blendedTea/blended13_2.png',
    title: '달빛걷기 35g',
    desc: '달큰한 배향이 달빛처럼 은은하게 감도는 후발효차',
    price: 15000,
    group: 'blendedtea',
    tag : '잎차',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/05_blendedTea/blended13_3.jpg'
  },
  {
    id: 'blended-014',
    imageOff: process.env.PUBLIC_URL + '/images/05_blendedTea/blended14_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/05_blendedTea/blended14_2.png',
    title: '달빛걷기 3입',
    desc: '달큰한 배향이 달빛처럼 은은하게 감도는 후발효차를 처음 접하시거나 다양한 차를 조금씩 맛보고 싶으시다면, 3입 제품으로 합리적인 가격에 체험해보세요.',
    price: 4500,
    group: 'blendedtea',
    tag : '티백',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/05_blendedTea/blended14_3.jpg'
  },
  {
    id: 'blended-015',
    imageOff: process.env.PUBLIC_URL + '/images/05_blendedTea/blended15_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/05_blendedTea/blended15_2.png',
    title: '달꽃이 바라보는 바당 10입',
    desc: '우아하고 화사한 꽃향과 사과의 풋풋함이 조화를 이룬 블렌디드 티',
    price: 15000,
    group: 'blendedtea',
    tag : '티백',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/05_blendedTea/blended15_3.jpg'
  },
  {
    id: 'blended-016',
    imageOff: process.env.PUBLIC_URL + '/images/05_blendedTea/blended16_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/05_blendedTea/blended16_2.png',
    title: '귤꽃향을 품은 우잣담 10입',
    desc: '제주 귤꽃향의 싱그러움에 감귤의 상큼함을 더한 블렌디드티를 소중한 사람에게 선물해보세요.',
    price: 15000,
    group: 'blendedtea',
    tag : '티백',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/05_blendedTea/blended16_3.jpg'
  },
  {
    id: 'blended-017',
    imageOff: process.env.PUBLIC_URL + '/images/05_blendedTea/blended17_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/05_blendedTea/blended17_2.png',
    title: '삼다연 제주영귤 10입',
    desc: '제주 삼나무의 그윽한 풍미에 제주영귤의 싱그러움을 더한 후발효차를 고급스러운 지함에 담았습니다. 소중한 사람에게 선물해보세요.',
    price: 15000,
    group: 'blendedtea',
    tag : '티백',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD: true,
    info : process.env.PUBLIC_URL + '/images/05_blendedTea/blended17_3.jpg'
  },
  {
    id: 'blended-018',
    imageOff: process.env.PUBLIC_URL + '/images/05_blendedTea/blended18_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/05_blendedTea/blended18_2.png',
    title: '삼다연 제주영귤 30g',
    desc: '제주 삼나무의 그윽한 풍미에 제주영귤의 싱그러움을 더한 후발효차를 원하는 용량만큼 우려드실 수 있는 잎차입니다. 합리적인 가격에 즐겨보세요.',
    price: 15000,
    group: 'blendedtea',
    tag : '잎차',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD: true,
    info : process.env.PUBLIC_URL + '/images/05_blendedTea/blended18_3.jpg'
  },
  {
    id: 'blended-019',
    imageOff: process.env.PUBLIC_URL + '/images/05_blendedTea/blended19_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/05_blendedTea/blended19_2.png',
    title: '제주 난꽃향 그린티 10입',
    desc: '1년에 단 10일만을 꽃 피우는 제주한란의 청아한 향을 담은 오리엔탈 그린티입니다. 소중한 사람에게 선물해보세요.',
    price: 15000,
    group: 'blendedtea',
    tag : '티백',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/05_blendedTea/blended19_3.jpg'
  },
  {
    id: 'blended-020',
    imageOff: process.env.PUBLIC_URL + '/images/05_blendedTea/blended20_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/05_blendedTea/blended20_2.png',
    title: '제주 삼다 영귤 티',
    desc: '제주 삼나무의 그윽한 풍미에 싱그러운 영귤의 상큼함이 매력적인 블렌디드 티입니다. 제주 차밭의 맛과 향을 가벼운 가격으로 즐겨보세요.',
    price: 9500,
    group: 'blendedtea',
    tag : '티백',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/05_blendedTea/blended20_3.jpg'
  },
  {
    id: 'blended-021',
    imageOff: process.env.PUBLIC_URL + '/images/05_blendedTea/blended21_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/05_blendedTea/blended21_2.png',
    title: '벚꽃향 가득한 올레 20입',
    desc: '제주 왕벚꽃향의 화사함에 달콤새콤한 과실향이 어우러진 블렌디드티',
    price: 23000,
    group: 'blendedtea',
    tag : '티백',
    new: false,
    count: 10,
    RD: true,
    typePack : '포장불가',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/05_blendedTea/blended21_3.jpg'
  },
  {
    id: 'blended-022',
    imageOff: process.env.PUBLIC_URL + '/images/05_blendedTea/blended22_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/05_blendedTea/blended22_2.png',
    title: '제주 유채&꿀 티',
    desc: '제주의 화사하고 향긋한 유채와 달달한 꿀을 블렌딩하여 따스한 블렌디드 티입니다. 제주 차밭의 맛과 향을 가벼운 가격으로 즐겨보세요.',
    price: 9500,
    group: 'blendedtea',
    tag : '티백',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/05_blendedTea/blended22_3.jpg'
  },
  {
    id: 'blended-023',
    imageOff: process.env.PUBLIC_URL + '/images/05_blendedTea/blended23_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/05_blendedTea/blended23_2.png',
    title: '달빛걷기 10입',
    desc: '달큰한 배향이 달빛처럼 은은하게 감도는 후발효차를 소중한 사람에게 선물해보세요',
    price: 15000,
    group: 'blendedtea',
    tag : '티백',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD: true,
    info : process.env.PUBLIC_URL + '/images/05_blendedTea/blended23_3.jpg'
  },
  {
    id: 'blended-024',
    imageOff: process.env.PUBLIC_URL + '/images/05_blendedTea/blended24_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/05_blendedTea/blended24_2.png',
    title: '삼다 꿀배 티',
    desc: '제주 밤바다처럼 그윽하고, 달큰한 배향이 환상적인 블렌디드티입니다. 제주 차밭의 맛과 향을 가벼운 가격으로 즐겨보세요.',
    price: 9500,
    group: 'blendedtea',
    tag : '티백',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/05_blendedTea/blended24_3.jpg'
  },
  {
    id: 'blended-025',
    imageOff: process.env.PUBLIC_URL + '/images/05_blendedTea/blended25_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/05_blendedTea/blended25_2.png',
    title: '웨딩 그린티 10입',
    desc: '신부의 부케가 꽃향이 만발하는 한잔의 차가 되었습니다. 소중한 사람에게 고급스러운 지함에 담긴 차를 선물해보세요.',
    price: 15000,
    group: 'blendedtea',
    tag : '티백',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD: true,
    info : process.env.PUBLIC_URL + '/images/05_blendedTea/blended25_3.jpg'
  },
  {
    id: 'blended-026',
    imageOff: process.env.PUBLIC_URL + '/images/05_blendedTea/blended26_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/05_blendedTea/blended26_2.png',
    title: '제주 동백꽃 티',
    desc: '제주 동백꽃의 달큰한 향미가 아찔하고 짙은 정열적이고 매혹적인 블렌디드 티입니다. 제주 차밭의 맛과 향을 가벼운 가격으로 즐겨보세요.',
    price: 9500,
    group: 'blendedtea',
    tag : '티백',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/05_blendedTea/blended26_3.jpg'
  },
  {
    id: 'blended-027',
    imageOff: process.env.PUBLIC_URL + '/images/05_blendedTea/blended27_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/05_blendedTea/blended27_2.png',
    title: '레드파파야 블랙티 10입',
    desc: '붉은 장미와 달콤한 파파야가 곁들여진 화려한 풍미의 홍차를 고급스러운 지함에 담았습니다. 소중한 사람에게 선물해보세요.',
    price: 15000,
    group: 'blendedtea',
    tag : '티백',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD: true,
    info : process.env.PUBLIC_URL + '/images/05_blendedTea/blended27_3.jpg'
  },
  {
    id: 'blended-028',
    imageOff: process.env.PUBLIC_URL + '/images/05_blendedTea/blended28_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/05_blendedTea/blended28_2.png',
    title: '동백이 피는 곶자왈 20입',
    desc: '제주 동백꽃향과 열대과일의 달콤한 풍미가 매력적인 블렌디드티',
    price: 15000,
    group: 'blendedtea',
    tag : '티백',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD: true,
    info : process.env.PUBLIC_URL + '/images/05_blendedTea/blended28_3.jpg'
  },
  {
    id: 'blended-029',
    imageOff: process.env.PUBLIC_URL + '/images/05_blendedTea/blended29_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/05_blendedTea/blended29_2.png',
    title: '웨딩 그린티 20입',
    desc: '신부의 부케가 꽃향이 만발하는 한잔의 차가 되었습니다. 피라미드 티백으로 간편하게, 합리적인 가격으로 즐겨보세요.',
    price: 23000,
    group: 'blendedtea',
    tag : '티백',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD: true,
    info : process.env.PUBLIC_URL + '/images/05_blendedTea/blended29_3.jpg'
  },
  {
    id: 'blended-030',
    imageOff: process.env.PUBLIC_URL + '/images/05_blendedTea/blended30_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/05_blendedTea/blended30_2.png',
    title: '삼다연 제주영귤 20입',
    desc: '제주 삼나무의 그윽한 풍미에 제주영귤의 싱그러움을 더한 후발효차를 피라미드 티백으로 간편하게, 합리적인 가격으로 즐겨보세요.',
    price: 23000,
    group: 'blendedtea',
    tag : '티백',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD: true,
    info : process.env.PUBLIC_URL + '/images/05_blendedTea/blended30_3.jpg'
  },
  {
    id: 'blended-031',
    imageOff: process.env.PUBLIC_URL + '/images/05_blendedTea/blended31_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/05_blendedTea/blended31_2.png',
    title: '달빛걷기 20입',
    desc: '달큰한 배향이 달빛처럼 은은하게 감도는 후발효차',
    price: 23000,
    group: 'blendedtea',
    tag : '티백',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD: true,
    info : process.env.PUBLIC_URL + '/images/05_blendedTea/blended31_3.jpg'
  },
  {
    id: 'blended-032',
    imageOff: process.env.PUBLIC_URL + '/images/05_blendedTea/blended32_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/05_blendedTea/blended32_2.png',
    title: '레드파파야 블랙티 20입',
    desc: '붉은 장미와 달콤한 파파야가 곁들여진 화려한 풍미의 홍차를 피라미드 티백으로 간편하게, 합리적인 가격으로 즐겨보세요.',
    price: 23000,
    group: 'blendedtea',
    tag : '티백',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD: true,
    info : process.env.PUBLIC_URL + '/images/05_blendedTea/blended32_3.jpg'
  },

  {
    id: 'herbal-001',
    imageOff: process.env.PUBLIC_URL + '/images/06_herbalTea/herbal01_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/06_herbalTea/herbal01_2.png',
    title: '루이보스 문라이트 10입',
    desc: '달큰한 배향이 달빛처럼 은은하게 감도는 블렌디드 루이보스차',
    price: 15000,
    group: 'blendedtea',
    tag : '티백',
    new: false,
    count: 0,
    typePack : '포장불가',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/06_herbalTea/herbal01_3.jpg'
  },
  {
    id: 'herbal-002',
    imageOff: process.env.PUBLIC_URL + '/images/06_herbalTea/herbal02_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/06_herbalTea/herbal02_2.png',
    title: '루이보스 퓨어 3입',
    desc: '붉은 태양을 닮은 깊은 풍미의 순수 루이보스차',
    price: 4500,
    group: 'blendedtea',
    tag : '티백',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/06_herbalTea/herbal02_3.jpg'
  },
  {
    id: 'herbal-003',
    imageOff: process.env.PUBLIC_URL + '/images/06_herbalTea/herbal03_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/06_herbalTea/herbal03_2.png',
    title: '루이보스 퓨어 20입',
    desc: '붉은 태양을 닮은 깊은 풍미의 순수 루이보스차',
    price: 23000,
    group: 'blendedtea',
    tag : '티백',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/06_herbalTea/herbal03_3.jpg'
  },
  {
    id: 'herbal-004',
    imageOff: process.env.PUBLIC_URL + '/images/06_herbalTea/herbal04_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/06_herbalTea/herbal04_2.png',
    title: '캐모마일 블렌드 10입',
    desc: '은은하고 달콤한 향의 블렌디드 캐모마일차',
    price: 15000,
    group: 'blendedtea',
    tag : '티백',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/06_herbalTea/herbal04_3.jpg'
  },
  {
    id: 'herbal-005',
    imageOff: process.env.PUBLIC_URL + '/images/06_herbalTea/herbal05_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/06_herbalTea/herbal05_2.png',
    title: '찬물 루이보스 티',
    desc: '찬물에서 쉽게 우러나는 깊고 진한 루이보스 보리 블렌드 스틱형 차',
    price: 9500,
    group: ['blendedtea', 'icedtea'],
    tag : '티백',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/06_herbalTea/herbal05_3.jpg'
  },
  {
    id: 'herbal-006',
    imageOff: process.env.PUBLIC_URL + '/images/06_herbalTea/herbal06_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/06_herbalTea/herbal06_2.png',
    title: '루이보스 퓨어 10입',
    desc: '붉은 태양을 닮은 깊은 풍미의 순수 루이보스차',
    price: 15000,
    group: 'blendedtea',
    tag : '티백',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD: true,
    info : process.env.PUBLIC_URL + '/images/06_herbalTea/herbal06_3.jpg'
  },
  {
    id: 'herbal-007',
    imageOff: process.env.PUBLIC_URL + '/images/06_herbalTea/herbal07_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/06_herbalTea/herbal07_2.png',
    title: '루이보스 카라멜베리 10입',
    desc: '붉은 태양을 닮은 깊은 풍미의 순수 루이보스차',
    price: 15000,
    group: 'blendedtea',
    tag : '티백',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD: true,
    info : process.env.PUBLIC_URL + '/images/06_herbalTea/herbal07_3.jpg'
  },
  {
    id: 'herbal-008',
    imageOff: process.env.PUBLIC_URL + '/images/06_herbalTea/herbal08_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/06_herbalTea/herbal08_2.png',
    title: '루이보스 카라멜베리 20입',
    desc: '달콤하게 즐기는 블렌디드 루이보스차입니다. 티백으로 간편하게, 합리적인 가격으로 즐겨보세요.',
    price: 23000,
    group: 'blendedtea',
    tag : '티백',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD: true,
    info : process.env.PUBLIC_URL + '/images/06_herbalTea/herbal08_3.jpg'
  },
  {
    id: 'herbal-009',
    imageOff: process.env.PUBLIC_URL + '/images/06_herbalTea/herbal09_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/06_herbalTea/herbal09_2.png',
    title: '모로칸 민트티 10입',
    desc: '기분좋은 상쾌함을 선사하는 허브차',
    price: 15000,
    group: 'blendedtea',
    tag : '티백',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/06_herbalTea/herbal09_3.jpg'
  },
  {
    id: 'herbal-010',
    imageOff: process.env.PUBLIC_URL + '/images/06_herbalTea/herbal10_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/06_herbalTea/herbal10_2.png',
    title: '스윗 베리 루이보스티',
    desc: '상큼한 라즈베리와 은은한 카라멜향이 조화롭게 어우러진 블렌디드 허브티',
    price: 9500,
    group: 'blendedtea',
    tag : '티백',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/06_herbalTea/herbal10_3.jpg'
  },

  {
    id: 'iced-001',
    imageOff: process.env.PUBLIC_URL + '/images/07_icedTea/iced01_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/07_icedTea/iced01_2.png',
    title: '콤부차 제주영귤 4입',
    desc: '상큼한 제주영귤 맛의 가볍게 즐기는, 녹차 유래 유산균 SCOBY로 만든 스파클링 콤부차! 탄산이 팡 터질 수 있으니 냉장 보관 후 주의해서 열어주세요!',
    price: 16000,
    group: 'icedtea',
    tag : '아이스티',
    new: false,
    count: 0,
    typePack : '포장불가',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/07_icedTea/iced01_3.jpg'
  },
  {
    id: 'iced-002',
    imageOff: process.env.PUBLIC_URL + '/images/07_icedTea/iced02_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/07_icedTea/iced02_2.png',
    title: '콤부차 피치동백 4입',
    desc: '달콤한 피치동백 맛의 가볍게 즐기는, 녹차 유래 유산균 SCOBY로 만든 스파클링 콤부차! 탄산이 팡 터질 수 있으니 냉장 보관 후 주의해서 열어주세요!',
    price: 16000,
    group: 'icedtea',
    tag : '아이스티',
    new: false,
    count: 0,
    typePack : '포장불가',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/07_icedTea/iced02_3.jpg'
  },
  {
    id: 'iced-003',
    imageOff: process.env.PUBLIC_URL + '/images/07_icedTea/iced03_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/07_icedTea/iced03_2.png',
    title: '콤부차 피치동백&제주영귤 4입',
    desc: '달콤한 피치동백 & 상큼한 제주영귤 맛의 가볍게 즐기는, 녹차 유래 유산균 SCOBY로 만든 스파클링 콤부차! 탄산이 팡 터질 수 있으니 냉장 보관 후 주의해서 열어주세요!',
    price: 16000,
    group: 'icedtea',
    tag : '아이스티',
    new: false,
    count: 0,
    typePack : '포장불가',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/07_icedTea/iced03_3.jpg'
  },
  {
    id: 'iced-004',
    imageOff: process.env.PUBLIC_URL + '/images/07_icedTea/iced04_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/07_icedTea/iced04_2.png',
    title: '콤부차 깔라망고 30입',
    desc: '상큼한 깔라만시와 달콤한 망고 블렌딩으로 맛있게, 찬물에도 잘 녹는 분말로 간편하게 즐기는 콤부차!',
    price: 24000,
    group: 'icedtea',
    tag : '아이스티',
    new: true,
    count: 10,
    typePack : '포장불가',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/07_icedTea/iced04_3.jpg'
  },
  {
    id: 'iced-005',
    imageOff: process.env.PUBLIC_URL + '/images/07_icedTea/iced05_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/07_icedTea/iced05_2.png',
    title: '콤부차 리치피치 30입',
    desc: '풍부한 달콤함의 리치 복숭아와 상큼한 히비스커스 블렌딩으로 맛있게, 찬물에도 잘 녹는 분말로 간편하게 즐기는 콤부차',
    price: 24000,
    group: 'icedtea',
    tag : '아이스티',
    new: true,
    count: 10,
    typePack : '포장불가',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/07_icedTea/iced05_3.jpg'
  },
  {
    id: 'iced-006',
    imageOff: process.env.PUBLIC_URL + '/images/07_icedTea/iced06_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/07_icedTea/iced06_2.png',
    title: '콤부차 리치피치 10입',
    desc: '풍부한 달콤함의 리치 복숭아와 상큼한 히비스커스 블렌딩으로 맛있게, 찬물에도 잘 녹는 분말로 간편하게 즐기는 콤부차',
    price: 8000,
    group: 'icedtea',
    tag : '아이스티',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/07_icedTea/iced06_3.jpg'
  },
  {
    id: 'iced-007',
    imageOff: process.env.PUBLIC_URL + '/images/07_icedTea/iced07_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/07_icedTea/iced07_2.png',
    title: '콤부차 깔라망고 10입',
    desc: '상큼한 깔라만시와 달콤한 망고 블렌딩으로 맛있게, 찬물에도 잘 녹는 분말로 간편하게 즐기는 콤부차',
    price: 8000,
    group: 'icedtea',
    tag : '아이스티',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/07_icedTea/iced07_3.jpg'
  },
  {
    id: 'iced-008',
    imageOff: process.env.PUBLIC_URL + '/images/07_icedTea/iced08_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/07_icedTea/iced08_2.png',
    title: '달빛섬 아이스티',
    desc: '제주 여름밤의 시원함을 담은 배향 아이스티입니다. 찬물에도 잘 우러나와 간편하게 즐기실 수 있습니다.',
    price: 13000,
    group: 'icedtea',
    tag : '아이스티',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/07_icedTea/iced08_3.jpg'
  },
  {
    id: 'iced-009',
    imageOff: process.env.PUBLIC_URL + '/images/07_icedTea/iced09_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/07_icedTea/iced09_2.png',
    title: '영귤섬 아이스티',
    desc: '제주 햇살 받고 자란 싱그러운 제주 영귤 아이스티입니다. 찬물에도 잘 우러나와 간편하게 즐기실 수 있습니다.',
    price: 16000,
    group: 'icedtea',
    tag : '아이스티',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/07_icedTea/iced09_3.jpg'
  },
  {
    id: 'iced-010',
    imageOff: process.env.PUBLIC_URL + '/images/07_icedTea/iced10_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/07_icedTea/iced10_2.png',
    title: '산호섬 아이스티',
    desc: '에메랄드빛 제주 바다를 닮은 머스캣향 아이스티입니다. 찬물에도 잘 우러나와 간편하게 즐기실 수 있습니다.',
    price: 13000,
    group: 'icedtea',
    tag : '아이스티',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD: true,
    info : process.env.PUBLIC_URL + '/images/07_icedTea/iced10_3.jpg'
  },
  {
    id: 'iced-011',
    imageOff: process.env.PUBLIC_URL + '/images/07_icedTea/iced11_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/07_icedTea/iced11_2.png',
    title: '삼다연 오리지널 밀크티',
    desc: '오설록 시그니처 발효차 삼다연 베이스의 오리지널 밀크티입니다.',
    price: 12000,
    group: 'icedtea',
    tag : '아이스티',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/07_icedTea/iced11_3.jpg'
  },
  {
    id: 'iced-012',
    imageOff: process.env.PUBLIC_URL + '/images/07_icedTea/iced12_1.png',
    imageOn: process.env.PUBLIC_URL + '/images/07_icedTea/iced12_2.png',
    title: '그린티 라떼 더블샷',
    desc: '녹차의 깊은 풍미를 두 배 더한 더블샷 라떼입니다.',
    price: 12000,
    group: 'icedtea',
    tag : '아이스티',
    new: false,
    count: 10,
    typePack : '포장불가',
    RD: false,
    info : process.env.PUBLIC_URL + '/images/07_icedTea/iced12_3.jpg'
  },
]

export default teaData